name: E2E Testing
on:
  push:
    branches:
      - "main"
jobs:
  E2E-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up github actions!
        uses: actions/checkout@v4

      - name: Install PHP Version!
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2 
          extensions: mbstring, intl, pdo_mysql, sodium

      - name: Set up MYSQL!
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "9.0"
          user: "test"
          password: "1234"

      - name: Setup Test in .env!
        run: echo "APP_ENV=test" >> .env

      - name: Install Dependencies!
        run: composer install

      - name: Create Database!
        run: php bin/console doctrine:database:create

      - name: Apply Migrations!
        run: php bin/console doctrine:migrations:migrate

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install node dependencies!
        run: npm install

      - name: Start PHP server!
        run: php -S 127.0.0.1:8000 -t public &

      - name: Run Cypress
        run: npm run cypress:run
      

