name: E2E Testing
on:
  push:
    branches:
      - "main"
jobs:
  E2E-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up github actions!
        uses: actions/checkout@v4

      - name: Install PHP Version!
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3.14"
          tools: composer:v2

      - name: Set up MYSQL!
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "9.0"
          user: "test"
          password: ""

      - name: Install Dependencies!
        run: composer install

      - name: Create Database!
        run: symfony d:d:c

      - name: Make Migration! 
        run: symfony make:migration

      - name: Apply Migration!
        run: symfony d:m:m
